### ISSUE TITLE
Bungee secured with TCPShield returning error: TIMED OUT

### ISSUE THREAD

**Issue by borodin0v** [Dinnerbone/mcstatus#156]
Code with getting response from server ![Screenshot_54](https://user-images.githubusercontent.com/47346535/130741353-edf5620b-bf05-499d-a8e0-d3377728cf9e.png)
Code making embed with data from returned array by get_ping_offline() ![Screenshot_55](https://user-images.githubusercontent.com/47346535/130741435-49190e01-8272-4477-aa6d-cf60bf9653c8.png)

And error:
`
someone queued to check magma online
Ignoring exception in command server:
Traceback (most recent call last):
  File "I:\coding\py\env\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "I:\coding\py\magmabot\modules\fun.py", line 54, in online_cmd
    embed.add_field(name='Пинг:', value='{0}'.format(bot_utils.get_ping_offline()[0]), inline=False)
  File "I:\coding\py\magmabot\bot_utils.py", line 77, in get_ping_offline
    qu = srv.query()
  File "I:\coding\py\env\lib\site-packages\mcstatus\server.py", line 170, in query
    raise exception_to_raise_after_giving_up
  File "I:\coding\py\env\lib\site-packages\mcstatus\server.py", line 165, in query
    querier.handshake()
  File "I:\coding\py\env\lib\site-packages\mcstatus\querier.py", line 48, in handshake
    packet = self._read_packet()
  File "I:\coding\py\env\lib\site-packages\mcstatus\querier.py", line 41, in _read_packet
    packet.receive(self.connection.read(self.connection.remaining()))
  File "I:\coding\py\env\lib\site-packages\mcstatus\protocol\connection.py", line 240, in read
    result.extend(self.socket.recvfrom(self.remaining())[0])
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "I:\coding\py\env\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "I:\coding\py\env\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "I:\coding\py\env\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
`
Using discord.py 1.7.3, mcstatus 6.5.0 (last release) and python 3.9

**Comment by Iapetus-11** [comment]
You should be using the lookup() function to perform that DNS SRV record lookup, that may fix it.

Also, you're using regular old blocking code in an async environment, that is bad, look into the [async methods of mcstatus](https://github.com/Dinnerbone/mcstatus/blob/10cea643fa3866063c6b5b327fe890213ecee7f2/mcstatus/server.py#L73) for your purpose or use a [ThreadPoolExecutor](https://docs.python.org/3/library/concurrent.futures.html). Mcstatus does not provide an async lookup() method so I created one in one of my old projects [here](https://github.com/Iapetus-11/Villager-API/blob/be07a3717034ccf51a625c21d669c0b1fccc778e/src/server.py#L109)

**Comment by kevinkjt2000** [comment]
Is this resolved now?
