### ISSUE TITLE
Cannot pickle mcstatus.pinger.PingResponse

### ISSUE THREAD

**Issue by winny-** [Dinnerbone/mcstatus#28]
Hi, I am not entirely certain what is going on here:

```
Python 3.4.2 (default, Oct 19 2014, 17:52:17)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.51)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pickle, mcstatus
>>> server = mcstatus.MinecraftServer('p.nerd.nu', 25565)
>>> result = server.status()
>>> pickle.dumps(result)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
_pickle.PicklingError: Can't pickle <class 'mcstatus.pinger.PingResponse.Players'>: attribute lookup Players on mcstatus.pinger failed
```

I originally found this through parallelizing server list pings using the multiprocessing module, with the following error (see the script here: https://gist.github.com/winny-/681fb7f8cf22ee23feb1/5841611b8d7a9d14b962a113c68bb5590834f7a6):

```
➜  mcstatus-py git:(master) python3 ~/Desktop/ping_servers.py
Traceback (most recent call last):
  File "/Users/winston/Desktop/ping_servers.py", line 98, in <module>
    main()
  File "/Users/winston/Desktop/ping_servers.py", line 80, in main
    for s in ping_servers_async(get_servers()):
  File "/Users/winston/Desktop/ping_servers.py", line 76, in ping_servers_async
    yield from pool.map(ping_server, servers)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/multiprocessing/pool.py", line 599, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: '[PingResult(server=Server(name='Bytesadism', ip='minecraft.bytesadism.org', port=25565), status=<mcstatus.pinger.PingResponse object at 0x1044e2a90>, error=None)]'. Reason: 'PicklingError("Can't pickle <class 'mcstatus.pinger.PingResponse.Version'>: attribute lookup Version on mcstatus.pinger failed",)'
```

**Comment by kevinkjt2000** [comment]
PRs are welcome on implementing the pickling capability.

**Comment by kevinkjt2000** [comment]
Given that unpickling data can be insecure, I'm choosing to reject this proposed feature.

https://docs.python.org/3/library/pickle.html
![image](https://user-images.githubusercontent.com/4098674/114311833-f4b20e80-9ab5-11eb-843f-5efc14724171.png)
