### ISSUE TITLE
[Errno 111] Connection refused

### ISSUE THREAD

**Issue by AndrewB6** [Dinnerbone/mcstatus#48]
I get this error after installing it with pip and trying to run "test.py" which is a copy of the usage code.

Traceback (most recent call last):
  File "test.py", line 7, in <module>
    status = server.status()
  File "/home/urbanmc/.local/lib/python2.7/site-packages/mcstatus/server.py", line 49, in status
    connection = TCPSocketConnection((self.host, self.port))
  File "/home/urbanmc/.local/lib/python2.7/site-packages/mcstatus/protocol/connection.py", line 129, in __init__
    self.socket = socket.create_connection(addr, timeout=timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 111] Connection refused

**Comment by AndrewB6** [comment]
Never mind, had wrong IP address entered.
