### ISSUE TITLE
ImportError: No module named 'dns'

### ISSUE THREAD

**Issue by creepersbane** [Dinnerbone/mcstatus#50]
Using Python 3.4 on Raspberry Pi
When importing the module, I get the following error:

Traceback (most recent call last):
  File "/home/pi/Python/conn/mcserver.py", line 1, in <module>
    from mcstatus import MinecraftServer
  File "/home/pi/Python/conn/mcstatus/__init__.py", line 1, in <module>
    from mcstatus.server import MinecraftServer
  File "/home/pi/Python/conn/mcstatus/server.py", line 4, in <module>
    import dns.resolver
ImportError: No module named 'dns'

What is the 'dns' module shown here?

**Comment by creepersbane** [comment]
nvm I used python 2.7 and it worked

**Comment by MarkL4YG** [comment]
Then I'd say the dns module got replaced or renamed in p3

**Comment by creepersbane** [comment]
I closed this issue for a reason, I just used python 2 and it worked
