### ISSUE TITLE
AttributeError: 'TCPSocketConnection' object has no attribute 'socket'

### ISSUE THREAD

**Issue by SirGhostal** [Dinnerbone/mcstatus#59]
Exception ignored in: <bound method TCPSocketConnection.__del__ of <mcstatus.protocol.connection.TCPSocketConnection object at 0x7fb1991eccc0>>
Traceback (most recent call last):
  File "/root/Factions-Discord-Bot/Factions-Discord-Bot/mcstatus/protocol/connection.py", line 153, in __del__
    self.socket.close()
AttributeError: 'TCPSocketConnection' object has no attribute 'socket'
Exception ignored in: <bound method TCPSocketConnection.__del__ of <mcstatus.protocol.connection.TCPSocketConnection object at 0x7fb19878e208>>
Traceback (most recent call last):
  File "/root/Factions-Discord-Bot/Factions-Discord-Bot/mcstatus/protocol/connection.py", line 153, in __del__
    self.socket.close()
AttributeError: 'TCPSocketConnection' object has no attribute 'socket'

**Comment by MarkL4YG** [comment]
#56

**Comment by kevinkjt2000** [comment]
Fixed in #56
