### ISSUE TITLE
ImportError: cannot import name MinecraftServer

### ISSUE THREAD

**Issue by brandonleon** [Dinnerbone/mcstatus#61]
Not sure where to begin troubleshooting this, if this is just an issue with my environment configuration let me know and I can continue to troubleshoot my system.

Trying to execute this in a script results in the same error.

```
root@Aluminium:/home/bleon# python
Python 2.7.13 (default, Nov 24 2017, 17:33:09)
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mcstatus
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mcstatus.py", line 1, in <module>
    from mcstatus import MinecraftServer
ImportError: cannot import name MinecraftServer
>>> from mcstatus import MinecraftServer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mcstatus.py", line 1, in <module>
    from mcstatus import MinecraftServer
ImportError: cannot import name MinecraftServer
>>>
```
however, running mcstatus from the command line works:

```
root@Aluminium:/home/bleon# mcstatus localhost status
version: v1.12.2 (protocol 340)
description: "{u'text': u'A Minecraft Server'}"
players: 0/20 No players online
```

**Comment by MarkL4YG** [comment]
Dont pin me on this but I would suggest trying ``from mcstatus.server import MinecraftServer``

**Comment by brandonleon** [comment]
Thank you for the follow up but I'm seeing the exact same thing when importing in that manner

```
bleon@Aluminium:~$ python
Python 2.7.13 (default, Nov 24 2017, 17:33:09)
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from mcstatus.server import MinecraftServer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mcstatus.py", line 1, in <module>
    from mcstatus import MinecraftServer
ImportError: cannot import name MinecraftServer
```

So I guess the underlying question I have here is if this is an issue with my environment or the library.

**Comment by brandonleon** [comment]
It might be worth noting I'm seeing this issue across multiple machines.

from a Raspberry Pi on my network:

```
~ » python                                                                                                                                          pi@openhab
Python 2.7.9 (default, Sep 17 2016, 20:26:04)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from mcstatus import MinecraftServer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mcstatus.py", line 1, in <module>
    from mcstatus import MinecraftServer
ImportError: cannot import name MinecraftServer
```

**Comment by MarkL4YG** [comment]
Being curious I quickly cloned the repo on an Ubuntu machine myself.  
Seems to work as expected using ``from mcstatus import MinecraftServer``.  

Did you run ``python setup.py build`` and ``python setup.py install`` in the cloned directory?

**Comment by kevinkjt2000** [comment]
@brandonleon Please share how you installed mcstatus to your machine.

**Comment by brandonleon** [comment]
I no longer have this machine running, please close this issue out.
