### ISSUE TITLE
Not working after a while.

### ISSUE THREAD

**Issue by DerpDays** [Dinnerbone/mcstatus#62]
```
Exception in command 'players'
Traceback (most recent call last):
  File "C:\Users\gameserver\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\gameserver\Desktop\Derps-Testing-Droid\cogs\players\players.py", line 20, in players
    ozquery = ozserver.query()
  File "C:\Users\gameserver\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mcstatus\server.py", line 82, in query
    raise exception
  File "C:\Users\gameserver\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mcstatus\server.py", line 77, in query
    querier.handshake()
  File "C:\Users\gameserver\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mcstatus\querier.py", line 30, in handshake
    self.connection.write(self._create_packet(self.PACKET_TYPE_CHALLENGE))
  File "C:\Users\gameserver\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mcstatus\protocol\connection.py", line 181, in write
    self.socket.sendto(data, self.addr)
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\gameserver\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "C:\Users\gameserver\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 514, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\gameserver\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 71, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: gaierror: [Errno 11001] getaddrinfo failed
```

I got this error after a bit Code:

```
import discord
from discord.ext import commands
from discord import utils
from mcstatus import MinecraftServer
import asyncio

class players:
    """Get the player count and display the data"""


    @commands.command(name="players")
    async def players(self, ctx):

        dwserver = MinecraftServer.lookup("direwolf.forgottenmc.net:25565")
        dwquery = dwserver.query()
        dwplayers = dwquery.players.online

        djserver = MinecraftServer.lookup("divine.forgottenmc.net:25565")
        djquery = djserver.query()
        djplayers = djquery.players.online

        ozserver = MinecraftServer.lookup("divine.forgottenmc.net:25565")
        ozquery = ozserver.query()
        ozplayers = ozquery.players.online

        vaserver = MinecraftServer.lookup("divine.forgottenmc.net:25565")
        vaquery = vaserver.query()
        vaplayers = vaquery.players.online


        embed = discord.Embed(title="Currently online", description="-----------------------", color=0xffffff)
        embed.add_field(name="Direwolf20: ", value=dwplayers)
        embed.add_field(name="Divine Journey: ", value=djplayers)
        embed.add_field(name="Ozone 2: ", value=ozplayers)
        embed.add_field(name="Vanilla: ", value=vaplayers)
        await ctx.send(embed=embed)


```

**Comment by DerpDays** [comment]
Gave up, the dev decided not to respond after months.

**Comment by MarkL4YG** [comment]
If you take a look around the repository you'll notice there're even older issues and proposals left unanswered. It appears @Dinnerbone abandoned this project long time ago.
