### ISSUE TITLE
query = server.query() throws socket.timeout: timed out

### ISSUE THREAD

**Issue by KironDevCoder** [Dinnerbone/mcstatus#71]
I'm trying to make a code to get notified when my friends come online on a server but apparently server.query() doesn't work?

    from mcstatus import MinecraftServer
    import time

    ip = input("IP: ")
    port = int(input("PORT: "))

    server = MinecraftServer(ip, port)

    while True:
        try:
            ping = server.status().latency
            print(f"PING: {ping}")
        except Exception as e:
            print(f"ERROR_PING: {str(e)}")

        try:
            query = server.query()
            print(f"PLAYERS: {query.players.names}")
        except Exception as e:
            print(f"ERROR_PLAYERS: {str(e)}")

        print("==========")
        time.sleep(10)

I used the ping to prove the server is running (the ping was pretty bad tbh, 367.996) but then `query = server.query()` throwed socket.timeout: timed out

    Traceback (most recent call last):
      File "<pyshell#6>", line 1, in <module>
        server.query()
      File "C:\Users\kiron\AppData\Local\Programs\Python\Python37\lib\site-packages\mcstatus\server.py", line 82, in query
        raise exception
      File "C:\Users\kiron\AppData\Local\Programs\Python\Python37\lib\site-packages\mcstatus\server.py", line 77, in query
        querier.handshake()
      File "C:\Users\kiron\AppData\Local\Programs\Python\Python37\lib\site-packages\mcstatus\querier.py", line 32, in handshake
        packet = self._read_packet()
      File "C:\Users\kiron\AppData\Local\Programs\Python\Python37\lib\site-packages\mcstatus\querier.py", line 25, in _read_packet
        packet.receive(self.connection.read(self.connection.remaining()))
      File "C:\Users\kiron\AppData\Local\Programs\Python\Python37\lib\site-packages\mcstatus\protocol\connection.py", line 178, in read
        result.extend(self.socket.recvfrom(self.remaining())[0])
    socket.timeout: timed out

**Comment by KironDevCoder** [comment]
just talked to the server owner, he said it might be possible the query can't get through cuz the server is behind a series of protections

**Comment by kevinkjt2000** [comment]
You are not alone in this.  Several have opened a similar issue https://github.com/Dinnerbone/mcstatus/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+query+timeout
I decided to open https://github.com/Dinnerbone/mcstatus/issues/72 to help others avoid this issue in the future.
