### ISSUE TITLE
I am using this and i am getting OSError when pinging a bungee proxy

### ISSUE THREAD

**Issue by XboxBedrock** [Dinnerbone/mcstatus#92]
Traceback (most recent call last):
  File "D:\Tools\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "D:\Tools\Python\Python38-32\lib\site-packages\discord\ext\commands\core.py", line 797, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "D:\Tools\Python\Python38-32\lib\site-packages\discord\ext\commands\core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: OSError: Server did not respond with any information!

(note im using this with discord.py)

**Comment by kevinkjt2000** [comment]
Read the error message: `Server did not respond with any information!`
Seems clear to me that the server is not responding...

**Comment by kevinkjt2000** [comment]
It's hard to help you any further than that given that you shared zero code that has anything to do with mcstatus. Check firewalls and other settings that could be preventing your communication with the server.
